In [1]:
import pandas as pd
import datetime as dt

In [2]:
data2016 = pd.read_csv("reservations2016.csv", encoding= 'unicode_escape')
data2016

,HistoricalReservationID,OrderNumber,Agency,OrgID,CodeHierarchy,RegionCode,RegionDescription,ParentLocationID,ParentLocation,LegacyFacilityID,...,Truck,Bus,Bicycle,Snowmobile,OffRoadlAllTerrainVehicle,PowerBoat,PickupCamper,LargeTentOver9x12,SmallTent,Marinaboat
0,2078081704,2-32732134,USACE,130,|1|70902|74304|74350|74559|71075|,CH3013280,OLD HICKORY LAKE,74350,NASHVILLE DISTRICT,71075,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2078083331,2-32732551,USFS,131,|1|70903|72602|74411|74812|70392|,F50755,OJAI RD - FS,74411,LOS PADRES NF -FS,70392,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2078083497,2-32732552,USFS,131,|1|70903|72602|74416|72724|75429|,F51753,YUBA RIVER RD -FS,74416,TAHOE NF - FS,75429,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2078083555,4-3155416,NPS,128,|1|70904|74324|77803|77813|,CAVE-7170,Carlsbad Caverns National Park,74324,Intermountain Region,77813,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2078083581,2-32732553,USFS,131,|1|70903|74311|74387|72667|70468|,F30406,RED ROCK RD -FS,74387,COCONINO NF - FS,70468,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2980709,2434322908,6-3050956,NPS,128,|1|70904|74325|74274|70853|,CAHA-5190,Cape Hatteras National Seashore,74325,Southeast Region,70853,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2980710,2434323098,4-3698992,NPS,128,|1|70904|74327|74292|135840|,SEKI-8550,Sequoia and Kings Canyon National Park,74327,Pacific West Region,135840,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2980711,2434324894,2-36683621,NPS,128,|1|70904|74324|74297|70923|,ZION-1590,Zion National Park,74324,Intermountain Region,70923,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2980712,2434324927,2-36683622,NPS,128,|1|70904|74324|74282|70971|,GRCA-8210,Grand Canyon National Park,74324,Intermountain Region,70971,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2980713,2434325007,2-36683623,USACE,130,|1|70902|74304|74349|74547|73073|,CH2000970,BARREN RIVER LAKE,74349,LOUISVILLE DIST.,73073,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
data2016.columns

Index(['HistoricalReservationID', 'OrderNumber', 'Agency', 'OrgID',
       'CodeHierarchy', 'RegionCode', 'RegionDescription', 'ParentLocationID',
       'ParentLocation', 'LegacyFacilityID', 'Park', 'SiteType', 'UseType',
       'ProductID', 'EntityType', 'EntityID', 'FacilityID', 'FacilityZIP',
       'FacilityState', 'FacilityLongitude', 'FacilityLatitude', 'CustomerZIP',
       'CustomerState', 'CustomerCountry', 'Tax', 'UseFee', 'TranFee',
       'AttrFee', 'TotalBeforeTax', 'TotalPaid', 'StartDate', 'EndDate',
       'OrderDate', 'NumberOfPeople', 'Tent', 'Popup', 'Trailer',
       'RVMotorhome', 'Boat', 'HorseTrailer', 'Car', 'FifthWheel', 'Van',
       'CanoeKayak', 'BoatTrailer', 'Motorcycle', 'Truck', 'Bus', 'Bicycle',
       'Snowmobile', 'OffRoadlAllTerrainVehicle', 'PowerBoat', 'PickupCamper',
       'LargeTentOver9x12', 'SmallTent', 'Marinaboat'],
      dtype='object')

In [4]:
data2016["EntityType"].unique()

array(['Site', 'Tour', 'Entrance', 'POS', nan], dtype=object)

In [5]:
data2016["UseType"].unique()

array(['Overnight', 'Day', 'None'], dtype=object)

In [6]:
data2016_clean = data2016.loc[(data2016["UseType"] == "Overnight") & (data2016["EntityType"] == "Site")]

In [7]:
data2016_clean["SiteType"].unique()

array(['STANDARD ELECTRIC', 'STANDARD NONELECTRIC',
       'TENT ONLY NONELECTRIC', 'RV NONELECTRIC', 'CABIN NONELECTRIC',
       'RV ELECTRIC', 'GROUP TENT ONLY AREA NONELECTRIC',
       'GROUP STANDARD NONELECTRIC', 'GROUP HIKE TO', 'HIKE TO',
       'GROUP STANDARD ELECTRIC', 'GROUP STANDARD AREA NONELECTRIC',
       'EQUESTRIAN ELECTRIC', 'OVERNIGHT SHELTER ELECTRIC',
       'GROUP WALK TO', 'GROUP RV AREA NONELECTRIC',
       'EQUESTRIAN NONELECTRIC', 'BOAT IN', 'WALK TO',
       'TENT ONLY ELECTRIC', 'CABIN ELECTRIC', 'MANAGEMENT', 'MOORING',
       'SHELTER NONELECTRIC', 'LOOKOUT', 'GROUP EQUESTRIAN',
       'GROUP SHELTER NONELECTRIC', 'GROUP STANDARD AREA ELECTRIC',
       'OVERNIGHT SHELTER NONELECTRIC', 'GROUP SHELTER ELECTRIC',
       'GROUP PICNIC AREA', 'YURT'], dtype=object)

In [8]:
data2016_clean.columns

Index(['HistoricalReservationID', 'OrderNumber', 'Agency', 'OrgID',
       'CodeHierarchy', 'RegionCode', 'RegionDescription', 'ParentLocationID',
       'ParentLocation', 'LegacyFacilityID', 'Park', 'SiteType', 'UseType',
       'ProductID', 'EntityType', 'EntityID', 'FacilityID', 'FacilityZIP',
       'FacilityState', 'FacilityLongitude', 'FacilityLatitude', 'CustomerZIP',
       'CustomerState', 'CustomerCountry', 'Tax', 'UseFee', 'TranFee',
       'AttrFee', 'TotalBeforeTax', 'TotalPaid', 'StartDate', 'EndDate',
       'OrderDate', 'NumberOfPeople', 'Tent', 'Popup', 'Trailer',
       'RVMotorhome', 'Boat', 'HorseTrailer', 'Car', 'FifthWheel', 'Van',
       'CanoeKayak', 'BoatTrailer', 'Motorcycle', 'Truck', 'Bus', 'Bicycle',
       'Snowmobile', 'OffRoadlAllTerrainVehicle', 'PowerBoat', 'PickupCamper',
       'LargeTentOver9x12', 'SmallTent', 'Marinaboat'],
      dtype='object')

In [9]:
data2016_clean = data2016_clean.drop(columns=['HistoricalReservationID', 
       'OrderNumber', 'OrgID', 'CodeHierarchy', 'RegionCode', 'ParentLocationID',
       'LegacyFacilityID', 'UseType', 'ProductID', 'EntityType', 'EntityID',
       'FacilityLongitude', 'FacilityLatitude', 'Tax', 'UseFee', 'TranFee',
       'AttrFee', 'TotalPaid', 'Tent', 'Popup', 'Trailer',
       'RVMotorhome', 'Boat', 'HorseTrailer', 'Car', 'FifthWheel', 'Van',
       'CanoeKayak', 'BoatTrailer', 'Motorcycle', 'Truck', 'Bus', 'Bicycle',
       'Snowmobile', 'OffRoadlAllTerrainVehicle', 'PowerBoat', 'PickupCamper',
       'LargeTentOver9x12', 'SmallTent', 'Marinaboat'])

In [10]:
data2016_clean.dtypes

Agency                object
RegionDescription     object
ParentLocation        object
Park                  object
SiteType              object
FacilityID           float64
FacilityZIP           object
FacilityState         object
CustomerZIP           object
CustomerState         object
CustomerCountry       object
TotalBeforeTax       float64
StartDate             object
EndDate               object
OrderDate             object
NumberOfPeople         int64
dtype: object

In [11]:
data2016_clean["StartDate"] = pd.to_datetime(data2016_clean["StartDate"])
data2016_clean["EndDate"] = pd.to_datetime(data2016_clean["EndDate"])
data2016_clean["OrderDate"] = pd.to_datetime(data2016_clean["OrderDate"])

In [12]:
data2016_clean.dtypes

Agency                       object
RegionDescription            object
ParentLocation               object
Park                         object
SiteType                     object
FacilityID                  float64
FacilityZIP                  object
FacilityState                object
CustomerZIP                  object
CustomerState                object
CustomerCountry              object
TotalBeforeTax              float64
StartDate            datetime64[ns]
EndDate              datetime64[ns]
OrderDate            datetime64[ns]
NumberOfPeople                int64
dtype: object

In [13]:
data2016_clean = data2016_clean.loc[(data2016_clean["StartDate"] >= "2016-05-01") 
                                    & (data2016_clean["EndDate"] <= "2016-09-30")]
data2016_clean

,Agency,RegionDescription,ParentLocation,Park,SiteType,FacilityID,FacilityZIP,FacilityState,CustomerZIP,CustomerState,CustomerCountry,TotalBeforeTax,StartDate,EndDate,OrderDate,NumberOfPeople
48,NPS,Joshua Tree National Park,Pacific West Region,SHEEP PASS GROUP,GROUP TENT ONLY AREA NONELECTRIC,232470.0,92277-3597,CA,90027,CA,USA,100.00,2016-09-03,2016-09-05,2015-10-01,20
96,USFS,MAMMOTH RD - FS,INYO NF - FS,PUMICE FLAT GROUP CAMP,GROUP STANDARD NONELECTRIC,231957.0,94301,CA,92301,CA,USA,313.05,2016-06-30,2016-07-03,2015-10-01,30
99,USFS,LOS ANGELES RIVER RD - FS,ANGELES NF - FS,MEADOW GROUP CAMPGROUND,GROUP STANDARD NONELECTRIC,233366.0,NaN,CA,91701,CA,USA,81.00,2016-06-24,2016-06-26,2015-10-01,24
236,NPS,Headquarters - Arches National Park,Arches National Park,DEVILS GARDEN CAMPGROUND,GROUP TENT ONLY AREA NONELECTRIC,234059.0,NaN,UT,84095,UT,USA,600.00,2016-06-14,2016-06-17,2015-10-01,40
243,USFS,NACHES RD - FS,OKANOGAN - WENATCHEE NF -FS,SALMON COVE GROUP SITE,GROUP STANDARD AREA NONELECTRIC,234498.0,98937,WA,98942,WA,USA,159.00,2016-09-08,2016-09-11,2015-10-01,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2979190,USACE,CARLYLE LAKE,ST. LOUIS DISTRICT,COLES CREEK REC AREA,STANDARD ELECTRIC,233463.0,62231,IL,62882,IL,USA,16.00,2016-09-29,2016-09-30,2016-09-30,5
2979639,USACE,MARK TWAIN LAKE,ST. LOUIS DISTRICT,INDIAN CREEK (MO),STANDARD ELECTRIC,233518.0,NaN,MO,62301,IL,USA,36.00,2016-07-31,2016-08-02,2016-09-30,8
2979811,USACE,MARK TWAIN LAKE,ST. LOUIS DISTRICT,INDIAN CREEK (MO),STANDARD ELECTRIC,233518.0,NaN,MO,65265,MO,USA,48.00,2016-08-08,2016-08-10,2016-09-30,8
2979817,USACE,MARK TWAIN LAKE,ST. LOUIS DISTRICT,RAY BEHRENS,STANDARD ELECTRIC,233597.0,NaN,MO,63401,MO,USA,48.00,2016-08-30,2016-09-01,2016-09-30,8
2979851,USACE,MARK TWAIN LAKE,ST. LOUIS DISTRICT,INDIAN CREEK (MO),STANDARD ELECTRIC,233518.0,NaN,MO,62305,IL,USA,48.00,2016-08-21,2016-08-23,2016-09-30,8

In [14]:
data2016_clean.to_csv("reservations_clean2016.csv", index = False, header=True)

In [16]:
data2017 = pd.read_csv("reservations2017.csv", encoding= 'unicode_escape')
data2017

,HistoricalReservationID,OrderNumber,Agency,OrgID,CodeHierarchy,RegionCode,RegionDescription,ParentLocationID,ParentLocation,LegacyFacilityID,...,Truck,Bus,Bicycle,Snowmobile,OffRoadlAllTerrainVehicle,PowerBoat,PickupCamper,LargeTentOver9x12,SmallTent,Marinaboat
0,2434304548,2-36681755,USFS,131,|1|70903|72601|72630|72684|71879|,F00531,SITKA RD - FS,72630,TONGASS NF - FS,71879,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2434322404,4-3699000,NPS,128,|1|70904|74268|77805|77815|,INDE-4450,Independence National Historical Park,74268,Northeast Region,77815,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2434322425,4-3699001,NPS,128,|1|70904|74327|72368|72369|,VALR,World War II Valor in the Pacific,74327,Pacific West Region,72369,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2434322473,4-3699002,NPS,128,|1|70904|74327|74292|135840|,SEKI-8550,Sequoia and Kings Canyon National Park,74327,Pacific West Region,135840,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2434322626,2-36683841,NPS,128,|1|70904|74324|74282|70971|,GRCA-8210,Grand Canyon National Park,74324,Intermountain Region,70971,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3303548,2830803631,4-4180361,NPS,128,|1|70904|74327|72368|72369|,VALR,World War II Valor in the Pacific,74327,Pacific West Region,72369,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3303549,2830803653,4-4180362,NPS,128,|1|70904|74327|72368|72369|,VALR,World War II Valor in the Pacific,74327,Pacific West Region,72369,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3303550,2830803670,2-39280451,NPS,128,|1|70904|74324|74282|70971|,GRCA-8210,Grand Canyon National Park,74324,Intermountain Region,70971,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3303551,2830803705,2-39280452,USACE,130,|1|70902|74306|74358|74590|73251|,CL3004990,LAKE SONOMA,74358,SAN FRANCISCO DIST,73251,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3303552,2830804361,4-4180282,NPS,128,|1|70904|74324|77803|77813|,CAVE-7170,Carlsbad Caverns National Park,74324,Intermountain Region,77813,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
data2017.columns

Index(['HistoricalReservationID', 'OrderNumber', 'Agency', 'OrgID',
       'CodeHierarchy', 'RegionCode', 'RegionDescription', 'ParentLocationID',
       'ParentLocation', 'LegacyFacilityID', 'Park', 'SiteType', 'UseType',
       'ProductID', 'EntityType', 'EntityID', 'FacilityID', 'FacilityZIP',
       'FacilityState', 'FacilityLongitude', 'FacilityLatitude', 'CustomerZIP',
       'CustomerState', 'CustomerCountry', 'Tax', 'UseFee', 'TranFee',
       'AttrFee', 'TotalBeforeTax', 'TotalPaid', 'StartDate', 'EndDate',
       'OrderDate', 'NumberOfPeople', 'Tent', 'Popup', 'Trailer',
       'RVMotorhome', 'Boat', 'HorseTrailer', 'Car', 'FifthWheel', 'Van',
       'CanoeKayak', 'BoatTrailer', 'Motorcycle', 'Truck', 'Bus', 'Bicycle',
       'Snowmobile', 'OffRoadlAllTerrainVehicle', 'PowerBoat', 'PickupCamper',
       'LargeTentOver9x12', 'SmallTent', 'Marinaboat'],
      dtype='object')

In [18]:
data2017["UseType"].unique()

array(['Overnight', 'Day', 'None'], dtype=object)

In [19]:
data2017["EntityType"].unique()

array(['Site', 'Tour', 'Entrance', 'POS'], dtype=object)

In [20]:
data2017_clean = data2017.loc[(data2017["UseType"] == "Overnight") & (data2017["EntityType"] == "Site")]

In [21]:
data2017_clean = data2017_clean.drop(columns=['HistoricalReservationID', 
       'OrderNumber', 'OrgID', 'CodeHierarchy', 'RegionCode', 'ParentLocationID',
       'LegacyFacilityID', 'UseType', 'ProductID', 'EntityType', 'EntityID',
       'FacilityLongitude', 'FacilityLatitude', 'Tax', 'UseFee', 'TranFee',
       'AttrFee', 'TotalPaid', 'Tent', 'Popup', 'Trailer',
       'RVMotorhome', 'Boat', 'HorseTrailer', 'Car', 'FifthWheel', 'Van',
       'CanoeKayak', 'BoatTrailer', 'Motorcycle', 'Truck', 'Bus', 'Bicycle',
       'Snowmobile', 'OffRoadlAllTerrainVehicle', 'PowerBoat', 'PickupCamper',
       'LargeTentOver9x12', 'SmallTent', 'Marinaboat'])

In [23]:
data2017_clean.dtypes

Agency                object
RegionDescription     object
ParentLocation        object
Park                  object
SiteType              object
FacilityID           float64
FacilityZIP           object
FacilityState         object
CustomerZIP           object
CustomerState         object
CustomerCountry       object
TotalBeforeTax       float64
StartDate             object
EndDate               object
OrderDate             object
NumberOfPeople         int64
dtype: object

In [24]:
data2017_clean["StartDate"] = pd.to_datetime(data2017_clean["StartDate"])
data2017_clean["EndDate"] = pd.to_datetime(data2017_clean["EndDate"])
data2017_clean["OrderDate"] = pd.to_datetime(data2017_clean["OrderDate"])

In [25]:
data2017_clean.dtypes

Agency                       object
RegionDescription            object
ParentLocation               object
Park                         object
SiteType                     object
FacilityID                  float64
FacilityZIP                  object
FacilityState                object
CustomerZIP                  object
CustomerState                object
CustomerCountry              object
TotalBeforeTax              float64
StartDate            datetime64[ns]
EndDate              datetime64[ns]
OrderDate            datetime64[ns]
NumberOfPeople                int64
dtype: object

In [26]:
data2017_clean = data2017_clean.loc[(data2017_clean["StartDate"] >= "2017-05-01") 
                                    & (data2017_clean["EndDate"] <= "2017-09-30")]
data2017_clean

,Agency,RegionDescription,ParentLocation,Park,SiteType,FacilityID,FacilityZIP,FacilityState,CustomerZIP,CustomerState,CustomerCountry,TotalBeforeTax,StartDate,EndDate,OrderDate,NumberOfPeople
55,NPS,Olympic National Park,Pacific West Region,SOL DUC HOT SPRINGS RESORT CAMPGROUND,STANDARD NONELECTRIC,251906.0,NaN,WA,97202,OR,USA,69.0,2017-07-01,2017-07-04,2016-10-01,8
104,USFS,SANTA CATALINA RD -FS,CORONADO NF - FS,WHITETAIL CAMPGROUND,GROUP STANDARD ELECTRIC,234564.0,NaN,AZ,85308,AZ,USA,749.0,2017-06-25,2017-06-30,2016-10-01,60
109,USFS,MONTEREY RD - FS,LOS PADRES NF -FS,ARROYO SECO,GROUP STANDARD NONELECTRIC,231958.0,NaN,CA,93907,CA,USA,159.0,2017-07-14,2017-07-16,2016-10-01,20
234,USFS,MT ADAMS RD - FS,GIFFORD PINCHOT NF - FS,Beaver Campground,GROUP STANDARD NONELECTRIC,232864.0,NaN,WA,98606,WA,USA,19.0,2017-08-03,2017-08-06,2016-10-01,40
286,NPS,Joshua Tree National Park,Pacific West Region,SHEEP PASS GROUP,GROUP TENT ONLY AREA NONELECTRIC,232470.0,92277-3597,CA,92694,CA,USA,60.0,2017-09-01,2017-09-04,2016-10-01,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3301381,USACE,CANTON LAKE,TULSA DISTRICT,SANDY COVE,STANDARD ELECTRIC,233619.0,NaN,OK,71203,LA,USA,80.0,2017-09-24,2017-09-28,2017-09-30,2
3301517,USACE,CANTON LAKE,TULSA DISTRICT,SANDY COVE,STANDARD ELECTRIC,233619.0,NaN,OK,79720,TX,USA,60.0,2017-09-22,2017-09-25,2017-09-30,2
3302666,USACE,ARKABUTLA LAKE,VICKSBURG DISTRICT,South Abutment Recreation Area,STANDARD ELECTRIC,233684.0,38618-6548,MS,38671,MS,USA,20.0,2017-09-29,2017-09-30,2017-09-30,5
3302670,USACE,ARKABUTLA LAKE,VICKSBURG DISTRICT,South Abutment Recreation Area,STANDARD ELECTRIC,233684.0,38618-6548,MS,38672,MS,USA,20.0,2017-09-29,2017-09-30,2017-09-30,4
3303000,USACE,MARK TWAIN LAKE,ST. LOUIS DISTRICT,RAY BEHRENS,STANDARD ELECTRIC,233597.0,NaN,MO,63383,MO,USA,18.0,2017-09-05,2017-09-06,2017-09-30,3

In [27]:
data2017_clean.to_csv ("reservations_clean2017.csv", index = False, header=True)

In [2]:
data2018 = pd.read_csv("reservations2018.csv", encoding= 'unicode_escape')
data2018

D:\anaconda3\envs\PythonData\lib\site-packages\IPython\core\interactiveshell.py:3072: DtypeWarning: Columns (12,17,29,31,55) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,HistoricalReservationID,OrderNumber,Agency,OrgID,CodeHierarchy,RegionCode,RegionDescription,ParentLocationID,ParentLocation,LegacyFacilityID,...,Bus,Bicycle,Snowmobile,OffRoadlAllTerrainVehicle,PowerBoat,PickupCamper,LargeTentOver9x12,SmallTent,Marinaboat,LatLongPoint
0,2976269875,4-4358197,NPS,128.0,|1|70904|74265|70710|70711|,KLGO-9825,Klondike Gold Rush National Historical Park,74265,Alaska Region,70711,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<e6100000 010cabaa aaaaaaba 4d40610b b6600bea ...
1,2976269875,4-4358197,NPS,128.0,|1|70904|74265|70710|70711|,KLGO-9825,Klondike Gold Rush National Historical Park,74265,Alaska Region,70711,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<e6100000 010cabaa aaaaaaba 4d40610b b6600bea ...
2,2976269875,4-4358197,NPS,128.0,|1|70904|74265|70710|70711|,KLGO-9825,Klondike Gold Rush National Historical Park,74265,Alaska Region,70711,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<e6100000 010cabaa aaaaaaba 4d40610b b6600bea ...
3,2976371845,4-4358345,NPS,128.0,|1|70904|74265|70710|70711|,KLGO-9825,Klondike Gold Rush National Historical Park,74265,Alaska Region,70711,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<e6100000 010cabaa aaaaaaba 4d40610b b6600bea ...
4,2976358486,4-4358374,NPS,128.0,|1|70904|74265|70710|70711|,KLGO-9825,Klondike Gold Rush National Historical Park,74265,Alaska Region,70711,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<e6100000 010cabaa aaaaaaba 4d40610b b6600bea ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3299800,3221486652,6-3833254,NPS,128.0,|1|70904|74322|74995|74996|,APIS-6140,Apostle Islands National Lakeshore,74322,Midwest Region,74996,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<e6100000 010c8888 88888878 47403a6d a0d306be ...
3299801,3221486652,6-3833254,NPS,128.0,|1|70904|74322|74995|74996|,APIS-6140,Apostle Islands National Lakeshore,74322,Midwest Region,74996,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<e6100000 010c8888 88888878 47403a6d a0d306be ...
3299802,3221486652,6-3833254,NPS,128.0,|1|70904|74322|74995|74996|,APIS-6140,Apostle Islands National Lakeshore,74322,Midwest Region,74996,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<e6100000 010c8888 88888878 47403a6d a0d306be ...
3299803,3221486652,6-3833254,NPS,128.0,|1|70904|74322|74995|74996|,APIS-6140,Apostle Islands National Lakeshore,74322,Midwest Region,74996,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<e6100000 010c8888 88888878 47403a6d a0d306be ...
3299804,3221486652,6-3833254,NPS,128.0,|1|70904|74322|74995|74996|,APIS-6140,Apostle Islands National Lakeshore,74322,Midwest Region,74996,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<e6100000 010c8888 88888878 47403a6d a0d306be ...

In [3]:
data2018.columns

Index(['HistoricalReservationID', 'OrderNumber', 'Agency', 'OrgID',
       'CodeHierarchy', 'RegionCode', 'RegionDescription', 'ParentLocationID',
       'ParentLocation', 'LegacyFacilityID', 'Park', 'SiteType', 'UseType',
       'ProductID', 'EntityType', 'EntityID', 'FacilityID', 'FacilityZIP',
       'FacilityState', 'FacilityLongitude', 'FacilityLatitude', 'CustomerZIP',
       'CustomerState', 'CustomerCountry', 'Tax', 'UseFee', 'TranFee',
       'AttrFee', 'TotalBeforeTax', 'TotalPaid', 'StartDate', 'EndDate',
       'OrderDate', 'NumberOfPeople', 'Tent', 'Popup', 'Trailer',
       'RVMotorhome', 'Boat', 'HorseTrailer', 'Car', 'FifthWheel', 'Van',
       'CanoeKayak', 'BoatTrailer', 'Motorcycle', 'Truck', 'Bus', 'Bicycle',
       'Snowmobile', 'OffRoadlAllTerrainVehicle', 'PowerBoat', 'PickupCamper',
       'LargeTentOver9x12', 'SmallTent', 'Marinaboat', 'LatLongPoint'],
      dtype='object')

In [4]:
data2018["UseType"].unique()

array([nan, 'Overnight', 'Day', 'OverNight'], dtype=object)

In [5]:
data2018["EntityType"].unique()

array(['Tour', 'Site', 'ERR'], dtype=object)

In [6]:
data2018_clean = data2018.loc[((data2018["UseType"] == "Overnight") | (data2018["UseType"] == "OverNight"))
                             & (data2018["EntityType"] == "Site")]

In [7]:
data2018_clean = data2018_clean.drop(columns=['HistoricalReservationID', 
       'OrderNumber', 'OrgID', 'CodeHierarchy', 'RegionCode', 'ParentLocationID',
       'LegacyFacilityID', 'UseType', 'ProductID', 'EntityType', 'EntityID',
       'FacilityLongitude', 'FacilityLatitude', 'Tax', 'UseFee', 'TranFee',
       'AttrFee', 'TotalPaid', 'Tent', 'Popup', 'Trailer',
       'RVMotorhome', 'Boat', 'HorseTrailer', 'Car', 'FifthWheel', 'Van',
       'CanoeKayak', 'BoatTrailer', 'Motorcycle', 'Truck', 'Bus', 'Bicycle',
       'Snowmobile', 'OffRoadlAllTerrainVehicle', 'PowerBoat', 'PickupCamper',
       'LargeTentOver9x12', 'SmallTent', 'Marinaboat', 'LatLongPoint'])

In [8]:
data2018_clean.dtypes

Agency                object
RegionDescription     object
ParentLocation        object
Park                  object
SiteType              object
FacilityID           float64
FacilityZIP           object
FacilityState         object
CustomerZIP           object
CustomerState         object
CustomerCountry       object
TotalBeforeTax       float64
StartDate             object
EndDate               object
OrderDate             object
NumberOfPeople       float64
dtype: object

In [9]:
data2018_clean["StartDate"] = pd.to_datetime(data2018_clean["StartDate"])
data2018_clean["EndDate"] = pd.to_datetime(data2018_clean["EndDate"])
data2018_clean["OrderDate"] = pd.to_datetime(data2018_clean["OrderDate"]).apply(lambda x: x.date())

In [10]:
data2018_clean.dtypes

Agency                       object
RegionDescription            object
ParentLocation               object
Park                         object
SiteType                     object
FacilityID                  float64
FacilityZIP                  object
FacilityState                object
CustomerZIP                  object
CustomerState                object
CustomerCountry              object
TotalBeforeTax              float64
StartDate            datetime64[ns]
EndDate              datetime64[ns]
OrderDate                    object
NumberOfPeople              float64
dtype: object

In [11]:
data2018_clean = data2018_clean.loc[(data2018_clean["StartDate"] >= "2018-05-01") 
                                    & (data2018_clean["EndDate"] <= "2018-09-30")]
data2018_clean

,Agency,RegionDescription,ParentLocation,Park,SiteType,FacilityID,FacilityZIP,FacilityState,CustomerZIP,CustomerState,CustomerCountry,TotalBeforeTax,StartDate,EndDate,OrderDate,NumberOfPeople
1294,USACE,MARK TWAIN LAKE,ST. LOUIS DISTRICT,Frank Russell Campground --- 02560013,EQUESTRIAN ELECTRIC,233501.0,63456-9359,MO,52658,IA,USA,36.0,2018-05-24,2018-05-28,2018-01-23,4.0
1297,USACE,MARK TWAIN LAKE,ST. LOUIS DISTRICT,Frank Russell Campground --- 02560013,EQUESTRIAN ELECTRIC,233501.0,63456-9359,MO,63461,MO,USA,36.0,2018-05-04,2018-05-06,2018-03-29,2.0
1298,USACE,MARK TWAIN LAKE,ST. LOUIS DISTRICT,Frank Russell Campground --- 02560013,EQUESTRIAN ELECTRIC,233501.0,63456-9359,MO,63383,MO,USA,10.0,2018-06-01,2018-06-03,2018-04-09,2.0
1299,USACE,MARK TWAIN LAKE,ST. LOUIS DISTRICT,Frank Russell Campground --- 02560013,EQUESTRIAN ELECTRIC,233501.0,63456-9359,MO,63383,MO,USA,10.0,2018-06-22,2018-06-24,2018-04-09,2.0
1305,USACE,MARK TWAIN LAKE,ST. LOUIS DISTRICT,Frank Russell Campground --- 02560013,EQUESTRIAN ELECTRIC,233501.0,63456-9359,MO,52351,IA,USA,18.0,2018-05-03,2018-05-04,2018-05-03,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3299471,USFS,HOOD CANAL RD - FS,OLYMPIC NF - FS,Coho Campground --- FPIN2427,YURT,233384.0,98376,WA,59602,MT,USA,80.0,2018-08-19,2018-08-20,2018-08-12,6.0
3299472,USFS,HOOD CANAL RD - FS,OLYMPIC NF - FS,Coho Campground --- FPIN2427,YURT,233384.0,98376,WA,98109,WA,USA,80.0,2018-09-02,2018-09-03,2018-08-17,2.0
3299473,USFS,HOOD CANAL RD - FS,OLYMPIC NF - FS,Coho Campground --- FPIN2427,YURT,233384.0,98376,WA,97302,OR,USA,220.0,2018-09-16,2018-09-19,2018-09-06,2.0
3299474,USACE,TIOGA-HAMMOND LAKE,BALTIMORE DISTRICT,Ives Run --- 40102001,STANDARD ELECTRIC,233523.0,16946-9733,PA,13903,NY,USA,108.0,2018-05-24,2018-05-27,2018-04-18,2.0
3299475,USACE,TIOGA-HAMMOND LAKE,BALTIMORE DISTRICT,Ives Run --- 40102001,STANDARD NONELECTRIC,233523.0,16946-9733,PA,17801,PA,USA,40.0,2018-05-25,2018-05-26,2018-05-25,2.0

In [12]:
data2018_clean["OrderDate"] = pd.to_datetime(data2018_clean["OrderDate"])

In [13]:
data2018_clean.dtypes

Agency                       object
RegionDescription            object
ParentLocation               object
Park                         object
SiteType                     object
FacilityID                  float64
FacilityZIP                  object
FacilityState                object
CustomerZIP                  object
CustomerState                object
CustomerCountry              object
TotalBeforeTax              float64
StartDate            datetime64[ns]
EndDate              datetime64[ns]
OrderDate            datetime64[ns]
NumberOfPeople              float64
dtype: object

In [14]:
data2018_clean.to_csv ("reservations_clean2018.csv", index = False, header=True)

In [2]:
data2019 = pd.read_csv("reservations2019.csv", encoding= 'unicode_escape')
data2019

D:\anaconda3\envs\PythonData\lib\site-packages\IPython\core\interactiveshell.py:3072: DtypeWarning: Columns (5,6,7,12,17,20,31,34) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,historicalreservationid,ordernumber,agency,orgid,codehierarchy,regioncode,regiondescription,parentlocationid,parentlocation,legacyfacilityid,...,attrfee,totalbeforetax,discount,totalpaid,startdate,enddate,orderdate,numberofpeople,equipmentdescription,equipmentlength
0,9c4a5398-4b50-4aa6-92fe-9a32699e49f9,0100084620-1,BLM,126.0,|1|70901|72193|72194|146090,AK,Alaska (BLM),72195,White Mountains National Recreation Area,146090.0,...,NaN,33.0,0.0,33.0,2019-01-26 00:00:00,2019-01-27 00:00:00,2018-12-27 20:54:55.233,4.0,NaN,0.0
1,4018a5bb-7e8a-49a1-bea2-f86be53b16e0,0100162496-1,BLM,126.0,|1|70901|72193|72194|146090,AK,Alaska (BLM),72195,White Mountains National Recreation Area,146090.0,...,NaN,18.0,0.0,18.0,2019-03-26 00:00:00,2019-03-27 00:00:00,2019-02-24 15:00:45.718,1.0,NaN,0.0
2,6458d681-584b-4e2b-b3f9-f398fa28f9eb,0100328335-1,BLM,126.0,|1|70901|72193|72194|146090,AK,Alaska (BLM),72195,White Mountains National Recreation Area,146090.0,...,NaN,33.0,0.0,33.0,2019-08-26 00:00:00,2019-08-27 00:00:00,2019-08-26 17:06:23.052,2.0,NaN,0.0
3,c4b1f737-44b8-46ca-ada4-523fe74a199c,0100404611-1,BLM,126.0,|1|70901|72193|72194|146090,AK,Alaska (BLM),72195,White Mountains National Recreation Area,146090.0,...,NaN,58.0,0.0,58.0,2018-11-23 00:00:00,2018-11-25 00:00:00,2018-10-23 00:23:58.275,5.0,NaN,0.0
4,e4f54fd0-2739-44a1-b807-bba4e3584e4a,0100444692-1,BLM,126.0,|1|70901|72193|72194|146090,AK,Alaska (BLM),72195,White Mountains National Recreation Area,146090.0,...,NaN,33.0,0.0,33.0,2019-08-28 00:00:00,2019-08-29 00:00:00,2019-08-15 18:33:22.488,2.0,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3479638,4-4609121-1,4-4609121-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,6.0,0.0,6.0,2018-11-02 00:00:00,NaN,2019-10-01 00:00:00,6.0,NaN,NaN
3479639,4-4618681-1,4-4618681-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,4.0,0.0,4.0,2018-11-04 00:00:00,NaN,2019-10-01 00:00:00,4.0,NaN,NaN
3479640,4-4626415-1,4-4626415-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,4.0,0.0,4.0,2018-11-20 00:00:00,NaN,2019-10-01 00:00:00,4.0,NaN,NaN
3479641,4-4628875-1,4-4628875-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,47.0,0.0,47.0,2018-12-08 00:00:00,NaN,2019-10-01 00:00:00,47.0,NaN,NaN
3479642,4-4635424-1,4-4635424-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3.0,0.0,3.0,2018-11-02 00:00:00,NaN,2019-10-01 00:00:00,3.0,NaN,NaN

In [3]:
data2019.columns

Index(['historicalreservationid', 'ordernumber', 'agency', 'orgid',
       'codehierarchy', 'regioncode', 'regiondescription', 'parentlocationid',
       'parentlocation', 'legacyfacilityid', 'park', 'sitetype', 'usetype',
       'productid', 'inventorytype', 'facilityid', 'facilityzip',
       'facilitystate', 'facilitylongitude', 'facilitylatitude', 'customerzip',
       'customerstate', 'customercountry', 'tax', 'usefee', 'tranfee',
       'attrfee', 'totalbeforetax', 'discount', 'totalpaid', 'startdate',
       'enddate', 'orderdate', 'numberofpeople', 'equipmentdescription',
       'equipmentlength'],
      dtype='object')

In [4]:
data2019["usetype"].unique()

array(['Overnight', nan, 'Day', 'Multi'], dtype=object)

In [5]:
data2019["inventorytype"].unique()

array(['CAMPING', 'PERMIT', 'TICKET', 'VEHICLE_PERMIT', 'LOTTERY_PERMIT',
       'RENTAL', 'LOTTERY_TICKET', 'LOTTERY_CAMPING'], dtype=object)

In [6]:
data2019_clean = data2019.loc[((data2019["usetype"] == "Overnight") | (data2019["usetype"] == "Multi"))
                            & ((data2019["inventorytype"] == "CAMPING") | (data2019["inventorytype"] == "LOTTERY_CAMPING"))]

In [7]:
data2019_clean.columns

Index(['historicalreservationid', 'ordernumber', 'agency', 'orgid',
       'codehierarchy', 'regioncode', 'regiondescription', 'parentlocationid',
       'parentlocation', 'legacyfacilityid', 'park', 'sitetype', 'usetype',
       'productid', 'inventorytype', 'facilityid', 'facilityzip',
       'facilitystate', 'facilitylongitude', 'facilitylatitude', 'customerzip',
       'customerstate', 'customercountry', 'tax', 'usefee', 'tranfee',
       'attrfee', 'totalbeforetax', 'discount', 'totalpaid', 'startdate',
       'enddate', 'orderdate', 'numberofpeople', 'equipmentdescription',
       'equipmentlength'],
      dtype='object')

In [8]:
data2019_clean = data2019_clean.drop(columns=['historicalreservationid', 'ordernumber', 'orgid',
       'codehierarchy', 'regioncode', 'parentlocationid',
       'legacyfacilityid', 'usetype',
       'productid', 'inventorytype', 'facilitylongitude', 'facilitylatitude', 'tax', 'usefee', 'tranfee',
       'attrfee', 'discount', 'totalpaid', 'equipmentdescription',
       'equipmentlength'])

In [9]:
data2019_clean.dtypes

agency                object
regiondescription     object
parentlocation        object
park                  object
sitetype              object
facilityid             int64
facilityzip          float64
facilitystate         object
customerzip           object
customerstate         object
customercountry       object
totalbeforetax       float64
startdate             object
enddate               object
orderdate             object
numberofpeople       float64
dtype: object

In [10]:
data2019_clean["startdate"] = pd.to_datetime(data2019_clean["startdate"])
data2019_clean["enddate"] = pd.to_datetime(data2019_clean["enddate"])
data2019_clean["orderdate"] = pd.to_datetime(data2019_clean["orderdate"]).apply(lambda x: x.date())

In [11]:
data2019_clean.dtypes

agency                       object
regiondescription            object
parentlocation               object
park                         object
sitetype                     object
facilityid                    int64
facilityzip                 float64
facilitystate                object
customerzip                  object
customerstate                object
customercountry              object
totalbeforetax              float64
startdate            datetime64[ns]
enddate              datetime64[ns]
orderdate                    object
numberofpeople              float64
dtype: object

In [12]:
data2019_clean = data2019_clean.loc[(data2019_clean["startdate"] >= "2019-05-01") 
                                    & (data2019_clean["enddate"] <= "2019-09-30")]
data2019_clean

,agency,regiondescription,parentlocation,park,sitetype,facilityid,facilityzip,facilitystate,customerzip,customerstate,customercountry,totalbeforetax,startdate,enddate,orderdate,numberofpeople
2,BLM,Alaska (BLM),White Mountains National Recreation Area,White Mountains National Recreation Area - Ala...,CABIN NONELECTRIC,252494,99730.0,Alaska,NaN,NaN,NaN,33.0,2019-08-26,2019-08-27,2019-08-26,2.0
4,BLM,Alaska (BLM),White Mountains National Recreation Area,White Mountains National Recreation Area - Ala...,CABIN NONELECTRIC,252494,99730.0,Alaska,99709,AK,USA,33.0,2019-08-28,2019-08-29,2019-08-15,2.0
6,BLM,Alaska (BLM),White Mountains National Recreation Area,White Mountains National Recreation Area - Ala...,CABIN NONELECTRIC,252494,99730.0,Alaska,NaN,NaN,NaN,58.0,2019-06-21,2019-06-23,2019-06-12,6.0
7,BLM,Alaska (BLM),White Mountains National Recreation Area,White Mountains National Recreation Area - Ala...,CABIN NONELECTRIC,252494,99730.0,Alaska,NaN,NaN,NaN,33.0,2019-05-05,2019-05-06,2019-04-26,4.0
8,BLM,Alaska (BLM),White Mountains National Recreation Area,White Mountains National Recreation Area - Ala...,CABIN NONELECTRIC,252494,99730.0,Alaska,NaN,NaN,NaN,33.0,2019-08-30,2019-08-31,2019-08-30,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3479460,USFS,NaN,NaN,HAYSTACK CAMPGROUND (EAST SHORE),STANDARD NONELECTRIC,234779,97734.0,Oregon,97471,NaN,NaN,53.0,2019-07-25,2019-07-28,2019-04-26,6.0
3479461,USFS,NaN,NaN,HAYSTACK CAMPGROUND (EAST SHORE),STANDARD NONELECTRIC,234779,97734.0,Oregon,97471,NaN,NaN,53.0,2019-07-25,2019-07-28,2019-04-26,6.0
3479462,USFS,NaN,NaN,HAYSTACK CAMPGROUND (EAST SHORE),STANDARD NONELECTRIC,234779,97734.0,Oregon,NaN,NaN,NaN,38.0,2019-07-12,2019-07-14,2019-05-13,3.0
3479463,USFS,NaN,NaN,HAYSTACK CAMPGROUND (EAST SHORE),STANDARD NONELECTRIC,234779,97734.0,Oregon,98446,WA,USA,23.0,2019-08-30,2019-08-31,2019-04-10,3.0
3479464,USFS,NaN,NaN,HAYSTACK CAMPGROUND (EAST SHORE),STANDARD NONELECTRIC,234779,97734.0,Oregon,98446,WA,USA,18.0,2019-08-30,2019-09-02,2019-04-10,4.0

In [13]:
data2019_clean["orderdate"] = pd.to_datetime(data2019_clean["orderdate"])

In [14]:
data2019_clean.dtypes

agency                       object
regiondescription            object
parentlocation               object
park                         object
sitetype                     object
facilityid                    int64
facilityzip                 float64
facilitystate                object
customerzip                  object
customerstate                object
customercountry              object
totalbeforetax              float64
startdate            datetime64[ns]
enddate              datetime64[ns]
orderdate            datetime64[ns]
numberofpeople              float64
dtype: object

In [15]:
data2019_clean.to_csv ("reservations_clean2019.csv", index = False, header=True)

In [16]:
data2020 = pd.read_csv("reservations2020.csv", encoding= 'unicode_escape')
data2020

D:\anaconda3\envs\PythonData\lib\site-packages\IPython\core\interactiveshell.py:3072: DtypeWarning: Columns (5,6,7,11,12,13,15,17,35) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,historicalreservationid,ordernumber,agency,orgid,codehierarchy,regioncode,regiondescription,parentlocationid,parentlocation,legacyfacilityid,...,totalbeforetax,discount,totalpaid,startdate,enddate,orderdate,nights,numberofpeople,equipmentdescription,equipmentlength
0,fa50401c-f08a-4738-b576-56335cc19cb7,0121072064-1,BLM,126,|1|70901|72193|72194|146090,AK,Alaska (BLM),72195,White Mountains National Recreation Area,146090.0,...,33.0,0.0,33.0,2019-10-17 00:00:00,2019-10-18 00:00:00,2019-09-18 16:25:42.28,1 day,6.0,NaN,0.0
1,09c37303-cf15-49d9-9b0c-ccc120328bbb,0200063847-1,BLM,126,|1|70901|72193|72194|146090,AK,Alaska (BLM),72195,White Mountains National Recreation Area,146090.0,...,33.0,0.0,33.0,2020-04-11 00:00:00,2020-04-12 00:00:00,2020-03-13 16:35:11.612,1 day,1.0,NaN,0.0
2,f1f5c841-46b1-4ff8-a6dc-fcac2e76ae1c,0200087454-1,BLM,126,|1|70901|72193|72194|146090,AK,Alaska (BLM),72195,White Mountains National Recreation Area,146090.0,...,83.0,0.0,83.0,2020-09-07 00:00:00,2020-09-10 00:00:00,2020-08-17 05:19:08.159,3 days,2.0,NaN,0.0
3,619f4394-1cac-4a64-8f0c-eae6e7f6bf3b,0200102788-1,BLM,126,|1|70901|72193|72194|146090,AK,Alaska (BLM),72195,White Mountains National Recreation Area,146090.0,...,33.0,0.0,33.0,2020-03-21 00:00:00,2020-03-22 00:00:00,2020-02-20 15:01:33.904,1 day,3.0,NaN,0.0
4,82674243-7f31-41e6-b3db-d0690513cad3,0200147542-1,BLM,126,|1|70901|72193|72194|146090,AK,Alaska (BLM),72195,White Mountains National Recreation Area,146090.0,...,0.0,0.0,0.0,2019-12-07 00:00:00,2019-12-08 00:00:00,2019-11-07 17:54:01.448,1 day,2.0,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5114784,3dc6db19-e935-11ea-b093-0a4663ab7691,0299936603-1,USFS,131,|1|70903|300017,NaN,NaN,14487,El Yunque National Forest,NaN,...,4.0,0.0,4.0,2020-09-05 00:00:00,2020-09-05 00:00:00,2020-08-28 13:49:44.115,00:00:00,2.0,NaN,NaN
5114785,31aa3a26-bf9f-11ea-9be3-ae918ba7a17b,0299948467-1,USFS,131,|1|70903|300017,NaN,NaN,14487,El Yunque National Forest,NaN,...,2.0,0.0,2.0,2020-07-17 00:00:00,2020-07-17 00:00:00,2020-07-06 15:43:44.14,00:00:00,1.0,NaN,NaN
5114786,abdea1e5-bfd3-11ea-b504-127b1cc19b77,0299955580-1,USFS,131,|1|70903|300017,NaN,NaN,14487,El Yunque National Forest,NaN,...,2.0,0.0,2.0,2020-07-12 00:00:00,2020-07-12 00:00:00,2020-07-06 22:00:34.837,00:00:00,1.0,NaN,NaN
5114787,8a06cee8-cd58-11ea-a075-5eeb99748ba8,0299963410-1,USFS,131,|1|70903|300017,NaN,NaN,14487,El Yunque National Forest,NaN,...,2.0,0.0,2.0,2020-07-30 00:00:00,2020-07-30 00:00:00,2020-07-24 02:52:17.583,00:00:00,0.0,NaN,NaN
5114788,5b63b296-c051-11ea-aec3-62673053eda9,0299996835-1,USFS,131,|1|70903|300017,NaN,NaN,14487,El Yunque National Forest,NaN,...,2.0,0.0,2.0,2020-08-02 00:00:00,2020-08-02 00:00:00,2020-07-07 12:58:51.219,00:00:00,0.0,NaN,NaN

In [17]:
data2020.columns

Index(['historicalreservationid', 'ordernumber', 'agency', 'orgid',
       'codehierarchy', 'regioncode', 'regiondescription', 'parentlocationid',
       'parentlocation', 'legacyfacilityid', 'park', 'sitetype', 'usetype',
       'productid', 'inventorytype', 'facilityid', 'facilityzip',
       'facilitystate', 'facilitylongitude', 'facilitylatitude', 'customerzip',
       'customerstate', 'customercountry', 'tax', 'usefee', 'tranfee',
       'attrfee', 'totalbeforetax', 'discount', 'totalpaid', 'startdate',
       'enddate', 'orderdate', 'nights', 'numberofpeople',
       'equipmentdescription', 'equipmentlength'],
      dtype='object')

In [18]:
data2020["usetype"].unique()

array(['Overnight', nan, 'Day', 'Activity', 'Multi'], dtype=object)

In [19]:
data2020["inventorytype"].unique()

array(['CAMPING', 'PERMIT', 'TICKET', 'VEHICLE_PERMIT', 'LOTTERY_PERMIT',
       'ACTIVITYPASS', 'RENTAL', 'LOTTERY_TICKET'], dtype=object)

In [20]:
data2020_clean = data2020.loc[((data2020["usetype"] == "Overnight") | (data2020["usetype"] == "Multi"))
                            & ((data2020["inventorytype"] == "CAMPING") | (data2020["inventorytype"] == "LOTTERY_CAMPING"))]

In [21]:
data2020_clean = data2020_clean.drop(columns=['historicalreservationid', 'ordernumber', 'orgid',
       'codehierarchy', 'regioncode', 'parentlocationid',
       'legacyfacilityid', 'usetype',
       'productid', 'inventorytype', 'facilitylongitude', 'facilitylatitude', 'tax', 'usefee', 'tranfee',
       'attrfee', 'discount', 'totalpaid', 'nights', 'equipmentdescription',
       'equipmentlength'])

In [22]:
data2020_clean.dtypes

agency                object
regiondescription     object
parentlocation        object
park                  object
sitetype              object
facilityid            object
facilityzip          float64
facilitystate         object
customerzip           object
customerstate         object
customercountry       object
totalbeforetax       float64
startdate             object
enddate               object
orderdate             object
numberofpeople       float64
dtype: object

In [23]:
data2020_clean["startdate"] = pd.to_datetime(data2020_clean["startdate"])
data2020_clean["enddate"] = pd.to_datetime(data2020_clean["enddate"])
data2020_clean["orderdate"] = pd.to_datetime(data2020_clean["orderdate"]).apply(lambda x: x.date())

In [24]:
data2020_clean.dtypes

agency                       object
regiondescription            object
parentlocation               object
park                         object
sitetype                     object
facilityid                   object
facilityzip                 float64
facilitystate                object
customerzip                  object
customerstate                object
customercountry              object
totalbeforetax              float64
startdate            datetime64[ns]
enddate              datetime64[ns]
orderdate                    object
numberofpeople              float64
dtype: object

In [25]:
data2020_clean["orderdate"] = pd.to_datetime(data2020_clean["orderdate"])

In [26]:
data2020_clean = data2020_clean.loc[(data2020_clean["startdate"] >= "2020-05-01") 
                                    & (data2020_clean["enddate"] <= "2020-09-30")]
data2020_clean

,agency,regiondescription,parentlocation,park,sitetype,facilityid,facilityzip,facilitystate,customerzip,customerstate,customercountry,totalbeforetax,startdate,enddate,orderdate,numberofpeople
2,BLM,Alaska (BLM),White Mountains National Recreation Area,White Mountains National Recreation Area - Ala...,CABIN NONELECTRIC,252494,99730.0,Alaska,99709-6072,NaN,NaN,83.0,2020-09-07,2020-09-10,2020-08-17,2.0
27,BLM,Alaska (BLM),White Mountains National Recreation Area,White Mountains National Recreation Area - Ala...,CABIN NONELECTRIC,252494,99730.0,Alaska,NaN,NaN,NaN,33.0,2020-09-19,2020-09-20,2020-09-11,2.0
35,BLM,Alaska (BLM),White Mountains National Recreation Area,White Mountains National Recreation Area - Ala...,CABIN NONELECTRIC,252494,99730.0,Alaska,99709,AK,USA,58.0,2020-05-22,2020-05-24,2020-04-25,2.0
60,BLM,Alaska (BLM),White Mountains National Recreation Area,White Mountains National Recreation Area - Ala...,CABIN NONELECTRIC,252494,99730.0,Alaska,99503,AK,USA,58.0,2020-06-26,2020-06-28,2020-05-28,2.0
74,BLM,Alaska (BLM),White Mountains National Recreation Area,White Mountains National Recreation Area - Ala...,CABIN NONELECTRIC,252494,99730.0,Alaska,99567,AK,USA,83.0,2020-06-23,2020-06-26,2020-06-03,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5107387,USFS,Eastern Region,Mark Twain National Forest,FUCHS HOUSE,CABIN ELECTRIC,273841,63952.0,Missouri,NaN,NaN,NaN,18.0,2020-07-27,2020-07-30,2020-06-15,5.0
5107388,USFS,Eastern Region,Mark Twain National Forest,FUCHS HOUSE,CABIN ELECTRIC,273841,63952.0,Missouri,63901,MO,USA,308.0,2020-09-04,2020-09-06,2020-02-26,15.0
5107389,USFS,Eastern Region,Mark Twain National Forest,FUCHS HOUSE,CABIN ELECTRIC,273841,63952.0,Missouri,63126,MO,USA,308.0,2020-09-11,2020-09-13,2020-08-11,2.0
5107390,USFS,Eastern Region,Mark Twain National Forest,FUCHS HOUSE,CABIN ELECTRIC,273841,63952.0,Missouri,NaN,NaN,NaN,308.0,2020-07-24,2020-07-26,2020-06-15,9.0
5107392,USFS,Eastern Region,Mark Twain National Forest,FUCHS HOUSE,CABIN ELECTRIC,273841,63952.0,Missouri,63042,MO,USA,308.0,2020-08-14,2020-08-16,2020-07-28,2.0

In [27]:
data2020_clean.to_csv ("reservations_clean2020.csv", index = False, header=True)